/**
 * Banco Piloto — 18 preguntas reales para validar la infraestructura
 *
 * Este banco sustituye temporalmente al banco completo cuando USE_PILOT_BANK=true.
 * Objetivo: validar componentes, motor, formatos mixtos, scoring por opción,
 *           importe manual, "Otro" con análisis IA, eliminación de Constructor.
 *
 * Distribución:
 *   6 fill_blank  — frases incompletas con desplegable
 *   6 choice      — preguntas completas con opciones
 *   6 amount      — escenarios de ahorro con importe manual
 *
 * Avatares cubiertos: comodo · social · impulsivo · desordenado
 * Constructor: NO existe ni como target ni en opciones.
 */

import type { DailyQuestion } from './dailyQuestionsBank';

// ═══════════════════════════════════════════════════════════════════════════════
// FILL_BLANK — Frases incompletas con desplegable + "Otro" con análisis IA
// ═══════════════════════════════════════════════════════════════════════════════

const Q_PILOT_FILL_BLANK: DailyQuestion[] = [
  {
    id: 'Q_P_01',
    format: 'fill_blank',
    text: 'Este gasto me cuesta evitarlo porque ____.',
    blankOptions: [
      {
        label: 'me apetece en el momento',
        value: 'apetece_momento',
        scores: { impulsivo: 2 },
      },
      {
        label: 'no quiero perderme el plan',
        value: 'fomo_plan',
        scores: { social: 2 },
      },
      {
        label: 'me resulta más cómodo',
        value: 'comodidad',
        scores: { comodo: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Resistencia al gasto',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Cualquiera',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'impulsivo',
    targetAvatarSecondary: 'social',
    scenarioWeight: 3,
    priorityBase: 10,
    cooldownDays: 5,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'resistencia_gasto',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_04',
    format: 'fill_blank',
    text: 'Cuando compro algo de impulso, después me siento más ____.',
    blankOptions: [
      {
        label: 'satisfecho/a, me lo merezco',
        value: 'satisfecho',
        scores: { impulsivo: 2 },
      },
      {
        label: 'culpable o arrepentido/a',
        value: 'culpable',
        scores: { impulsivo: 3, desordenado: 1 },
      },
      {
        label: 'indiferente, ya está hecho',
        value: 'indiferente',
        scores: { desordenado: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Emoción post-gasto',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'impulsivo',
    targetAvatarSecondary: 'desordenado',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 7,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'emociones_compra_impulsiva',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_07',
    format: 'fill_blank',
    text: 'Al revisar mis gastos del mes, lo que más me sorprende es ____.',
    blankOptions: [
      {
        label: 'cuánto gasto en comodidad y conveniencia',
        value: 'comodidad_conveniencia',
        scores: { comodo: 2 },
      },
      {
        label: 'lo que me he gastado saliendo con gente',
        value: 'gasto_social',
        scores: { social: 2 },
      },
      {
        label: 'los gastos pequeños que ni recuerdo',
        value: 'gastos_invisibles',
        scores: { desordenado: 3 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Conciencia financiera',
    bestDays: 'Domingo, Lunes',
    bestTimeWindow: 'Mañana',
    monthPhase: 'Final',
    targetAvatarPrimary: 'desordenado',
    targetAvatarSecondary: 'comodo',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 14,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'revision_mensual',
    habit_principle: 'satisfying',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_10',
    format: 'fill_blank',
    text: 'Cuando salgo con amigos, lo más difícil para mí es ____.',
    blankOptions: [
      {
        label: 'decir que no a más consumiciones o rondas',
        value: 'no_rondas',
        scores: { social: 2 },
      },
      {
        label: 'seguir el plan que tenía pensado',
        value: 'plan_previo',
        scores: { desordenado: 2 },
      },
      {
        label: 'no gastar en lo primero que me apetece',
        value: 'impulso_social',
        scores: { impulsivo: 2, social: 1 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Control en planes sociales',
    bestDays: 'Viernes, Sábado, Domingo',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'social',
    targetAvatarSecondary: 'impulsivo',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 5,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'friccion_planes_sociales',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_13',
    format: 'fill_blank',
    text: 'Si tuviera que cambiar un hábito de gasto, empezaría por ____.',
    blankOptions: [
      {
        label: 'pedir menos delivery y cocinar más',
        value: 'menos_delivery',
        scores: { comodo: 2 },
      },
      {
        label: 'controlar mejor lo que gasto saliendo',
        value: 'control_social',
        scores: { social: 2 },
      },
      {
        label: 'resistir los impulsos de comprar cosas',
        value: 'resistir_impulsos',
        scores: { impulsivo: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Hábito a cambiar',
    bestDays: 'Lunes, Domingo',
    bestTimeWindow: 'Mañana',
    monthPhase: 'Inicio',
    targetAvatarPrimary: 'comodo',
    targetAvatarSecondary: 'impulsivo',
    scenarioWeight: 3,
    priorityBase: 8,
    cooldownDays: 14,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'habito_a_cambiar',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_16',
    format: 'fill_blank',
    text: 'Cuando tengo estrés o me siento bajo/a, tiendo a ____.',
    blankOptions: [
      {
        label: 'buscar algo cómodo que me relaje',
        value: 'buscar_comodidad',
        scores: { comodo: 2 },
      },
      {
        label: 'quedar con alguien o salir',
        value: 'salir_social',
        scores: { social: 2 },
      },
      {
        label: 'comprarme algo para sentirme mejor',
        value: 'compra_emocional',
        scores: { impulsivo: 3 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Gestión emocional',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'impulsivo',
    targetAvatarSecondary: 'comodo',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 7,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'compra_emocional_estres',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'medium',
    experimental: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// CHOICE — Preguntas completas con opciones + "Otro" con análisis IA
// ═══════════════════════════════════════════════════════════════════════════════

const Q_PILOT_CHOICE: DailyQuestion[] = [
  {
    id: 'Q_P_02',
    format: 'choice',
    text: '¿Qué te impulsa más a gastar en planes con otras personas?',
    choiceOptions: [
      {
        label: 'El miedo a perderme algo bueno',
        value: 'fomo',
        scores: { social: 2 },
      },
      {
        label: 'La comodidad de decir que sí sin pensar',
        value: 'comodidad_si',
        scores: { comodo: 2 },
      },
      {
        label: 'El momento me pide celebrar o gastar',
        value: 'impulso_momento',
        scores: { impulsivo: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Motivación gasto social',
    bestDays: 'Jueves, Viernes, Sábado',
    bestTimeWindow: 'Tarde',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'social',
    targetAvatarSecondary: 'impulsivo',
    scenarioWeight: 3,
    priorityBase: 10,
    cooldownDays: 5,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'motivacion_gasto_social',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_05',
    format: 'choice',
    text: 'Cuando decides pedir delivery en vez de cocinar, ¿qué pesa más?',
    choiceOptions: [
      {
        label: 'La pereza y las ganas de comodidad',
        value: 'pereza_comodidad',
        scores: { comodo: 2 },
      },
      {
        label: 'Que no tengo nada planificado',
        value: 'sin_plan',
        scores: { desordenado: 2 },
      },
      {
        label: 'Me apetece ese momento y ya',
        value: 'apetece_ahora',
        scores: { impulsivo: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 10,
    habitCategory: 'Delivery',
    bestDays: 'Lunes, Martes, Miércoles, Jueves',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'comodo',
    targetAvatarSecondary: 'desordenado',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 3,
    monthlyDelta: 40,
    yearlyDelta: 480,
    labelImpact: 'Cocinar en casa en vez de delivery ahorra ~40 €/mes',
    active: true,
    intent: 'motivacion_delivery',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_08',
    format: 'choice',
    text: 'Cuando ves algo que quieres pero no necesitas, ¿qué sueles hacer?',
    choiceOptions: [
      {
        label: 'Lo compro si el precio me parece razonable',
        value: 'compra_precio',
        scores: { impulsivo: 2 },
      },
      {
        label: 'Lo apunto y espero unos días antes de decidir',
        value: 'esperar_dias',
        scores: { desordenado: 1, comodo: 1 },
      },
      {
        label: 'Lo compro si estoy con alguien que también lo haría',
        value: 'influencia_social',
        scores: { social: 2, impulsivo: 1 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Reacción ante tentación',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Tarde',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'impulsivo',
    targetAvatarSecondary: 'social',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 7,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'reaccion_tentacion',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_11',
    format: 'choice',
    text: '¿Cuál describe mejor cómo gestionas tu dinero en el día a día?',
    choiceOptions: [
      {
        label: 'Gasto y ya veré cómo va el mes',
        value: 'sin_control',
        scores: { desordenado: 2 },
      },
      {
        label: 'Gasto en lo que me resulta fácil y cómodo, sin pensar mucho',
        value: 'comodidad_automatica',
        scores: { comodo: 2 },
      },
      {
        label: 'Gasto según lo que me pide el momento',
        value: 'gasto_momento',
        scores: { impulsivo: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Estilo de gestión',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Mañana',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'desordenado',
    targetAvatarSecondary: 'comodo',
    scenarioWeight: 3,
    priorityBase: 10,
    cooldownDays: 10,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'diagnostico_gestion',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_14',
    format: 'choice',
    text: 'Cuando el grupo propone un plan que se sale de tu presupuesto, normalmente...',
    choiceOptions: [
      {
        label: 'Digo que sí aunque me pase del presupuesto',
        value: 'si_sin_limite',
        scores: { social: 3 },
      },
      {
        label: 'Me apunto porque en ese momento me parece buena idea',
        value: 'impulso_grupo',
        scores: { impulsivo: 2, social: 1 },
      },
      {
        label: 'Propongo algo más barato o ajustado',
        value: 'propongo_barato',
        scores: { comodo: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Presión social',
    bestDays: 'Jueves, Viernes, Sábado',
    bestTimeWindow: 'Tarde',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'social',
    targetAvatarSecondary: 'impulsivo',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 5,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'presion_social_gasto',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_17',
    format: 'choice',
    text: '¿Qué tipo de plan de fin de semana prefieres?',
    choiceOptions: [
      {
        label: 'Algo tranquilo, sin sorpresas y a mi ritmo',
        value: 'plan_tranquilo',
        scores: { comodo: 2 },
      },
      {
        label: 'Un plan con gente, aunque cueste más de lo esperado',
        value: 'plan_gente',
        scores: { social: 2 },
      },
      {
        label: 'Lo que surja, improvisando sobre la marcha',
        value: 'plan_impro',
        scores: { desordenado: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 0,
    habitCategory: 'Preferencia ocio',
    bestDays: 'Viernes, Sábado',
    bestTimeWindow: 'Tarde',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'comodo',
    targetAvatarSecondary: 'social',
    scenarioWeight: 2,
    priorityBase: 8,
    cooldownDays: 7,
    monthlyDelta: 0,
    yearlyDelta: 0,
    labelImpact: '',
    active: true,
    intent: 'preferencia_ocio_finde',
    habit_principle: 'attractive',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// AMOUNT — Escenarios de ahorro con importe manual obligatorio
// ═══════════════════════════════════════════════════════════════════════════════

const Q_PILOT_AMOUNT: DailyQuestion[] = [
  {
    id: 'Q_P_03',
    format: 'amount',
    text: 'Si hoy has revisado tus suscripciones y cancelado o reducido alguna que no usabas, ¿cuánto te ahorras al mes?',
    suggestedAmount: 8,
    habitCategory: 'Suscripciones',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Mañana',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'desordenado',
    targetAvatarSecondary: '',
    scenarioWeight: 3,
    priorityBase: 8,
    cooldownDays: 14,
    monthlyDelta: 12,
    yearlyDelta: 144,
    labelImpact: 'Las suscripciones olvidadas cuestan ~12 €/mes',
    active: true,
    intent: 'control_suscripciones',
    habit_principle: 'satisfying',
    tone: 'motivador',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_06',
    format: 'amount',
    text: 'Si hoy has rechazado un plan caro o propuesto una alternativa más barata a tus amigos, ¿cuánto has ahorrado?',
    suggestedAmount: 15,
    habitCategory: 'Planes sociales',
    bestDays: 'Jueves, Viernes, Sábado',
    bestTimeWindow: 'Tarde',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'social',
    targetAvatarSecondary: '',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 3,
    monthlyDelta: 45,
    yearlyDelta: 540,
    labelImpact: 'Proponer alternativas baratas ahorra ~45 €/mes',
    active: true,
    intent: 'control_gasto_social',
    habit_principle: 'attractive',
    tone: 'motivador',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_09',
    format: 'amount',
    text: 'Si hoy has preparado comida en casa en vez de pedir delivery, ¿cuánto has ahorrado?',
    suggestedAmount: 10,
    habitCategory: 'Delivery',
    bestDays: 'Lunes, Martes, Miércoles, Jueves',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'comodo',
    targetAvatarSecondary: '',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 2,
    monthlyDelta: 48,
    yearlyDelta: 576,
    labelImpact: 'Cocinar en casa evita ~4 pedidos semanales de más',
    active: true,
    intent: 'delivery_conveniencia',
    habit_principle: 'easy',
    tone: 'motivador',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_12',
    format: 'amount',
    text: 'Si hoy has cerrado una app de compras o ignorado una oferta flash sin comprar nada, ¿cuánto crees que has evitado gastar?',
    suggestedAmount: 20,
    habitCategory: 'Compra impulsiva',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'impulsivo',
    targetAvatarSecondary: '',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 3,
    monthlyDelta: 40,
    yearlyDelta: 480,
    labelImpact: 'Cerrar apps de compras sin comprar ahorra ~40 €/mes',
    active: true,
    intent: 'resistencia_compra_impulsiva',
    habit_principle: 'obvious',
    tone: 'motivador',
    difficulty: 'high',
    experimental: true,
  },
  {
    id: 'Q_P_15',
    format: 'amount',
    text: 'Si hoy has identificado un gasto "invisible" que haces casi cada día sin notarlo (café, vending, app…), ¿cuánto suma al mes?',
    suggestedAmount: 5,
    habitCategory: 'Microfugas',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'desordenado',
    targetAvatarSecondary: 'comodo',
    scenarioWeight: 2,
    priorityBase: 8,
    cooldownDays: 5,
    monthlyDelta: 20,
    yearlyDelta: 240,
    labelImpact: 'Identificar microfugas es el primer paso para pararlas',
    active: true,
    intent: 'conciencia_microfugas',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_18',
    format: 'amount',
    text: 'Si esta semana has controlado los gastos en salidas nocturnas (copas extra, taxis, rondas), ¿cuánto menos has gastado de lo normal?',
    suggestedAmount: 15,
    habitCategory: 'Escalada social',
    bestDays: 'Lunes, Domingo',
    bestTimeWindow: 'Mañana',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'social',
    targetAvatarSecondary: 'impulsivo',
    scenarioWeight: 3,
    priorityBase: 8,
    cooldownDays: 7,
    monthlyDelta: 45,
    yearlyDelta: 540,
    labelImpact: 'Controlar las noches que se alargan ahorra ~45 €/mes',
    active: true,
    intent: 'control_escalada_social',
    habit_principle: 'satisfying',
    tone: 'motivador',
    difficulty: 'high',
    experimental: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// Banco piloto completo
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * 18 preguntas piloto funcionales y listas para test.
 * Distribuidas en: 6 fill_blank + 6 choice + 6 amount.
 * Cubren los 4 avatares activos: comodo, social, impulsivo, desordenado.
 * Constructor: eliminado de toda la lógica.
 */
export const PILOT_QUESTIONS_BANK: DailyQuestion[] = [
  ...Q_PILOT_FILL_BLANK,
  ...Q_PILOT_CHOICE,
  ...Q_PILOT_AMOUNT,
];
