/**
 * Banco Piloto — 12 preguntas reales para validar la infraestructura
 *
 * Este banco sustituye temporalmente al banco completo cuando USE_PILOT_BANK=true.
 * Objetivo: validar componentes, motor, formatos mixtos, scoring por opción,
 *           importe manual, "Otro" con análisis IA.
 *
 * Distribución:
 *   6 fill_blank  — frases de ahorro con hueco y desplegable
 *   6 amount      — escenarios de ahorro con importe manual
 *
 * Avatares cubiertos: comodo · social · impulsivo · desordenado
 */

import type { DailyQuestion } from './dailyQuestionsBank';

// ═══════════════════════════════════════════════════════════════════════════════
// FILL_BLANK — Frases incompletas con desplegable + "Otro" con análisis IA
// ═══════════════════════════════════════════════════════════════════════════════

const Q_PILOT_FILL_BLANK: DailyQuestion[] = [
  {
    id: 'Q_P_01',
    format: 'fill_blank',
    text: 'Hoy he resistido gastar dinero en ____.',
    blankOptions: [
      {
        label: 'algo que me apetec\u00eda en ese momento sin necesitarlo',
        value: 'apetece_momento',
        scores: { impulsivo: 2 },
      },
      {
        label: 'una compra de impulso que habr\u00eda lamentado despu\u00e9s',
        value: 'compra_impulso',
        scores: { impulsivo: 2 },
      },
      {
        label: 'un plan caro que no me apetec\u00eda realmente',
        value: 'plan_social',
        scores: { social: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 15,
    habitCategory: 'Resistencia al impulso',
    bestDays: 'Cualquier d\u00eda',
    bestTimeWindow: 'Tarde',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'impulsivo',
    targetAvatarSecondary: 'social',
    scenarioWeight: 3,
    priorityBase: 10,
    cooldownDays: 4,
    monthlyDelta: 45,
    yearlyDelta: 540,
    labelImpact: 'Resistir impulsos ahorra ~45 \u20ac/mes',
    active: true,
    intent: 'gasto_evitado_impulso_piloto',
    habit_principle: 'obvious',
    tone: 'motivador',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_04',
    format: 'fill_blank',
    text: 'Esta semana he preparado en casa lo que antes compraba fuera: ____.',
    blankOptions: [
      {
        label: 'el almuerzo o t\u00e1per para el trabajo',
        value: 'taper_trabajo',
        scores: { comodo: 2 },
      },
      {
        label: 'el desayuno o caf\u00e9 de la ma\u00f1ana',
        value: 'desayuno_casa',
        scores: { comodo: 2 },
      },
      {
        label: 'la cena, planificando en vez de improvisar',
        value: 'cena_planificada',
        scores: { desordenado: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 8,
    habitCategory: 'Comida en casa',
    bestDays: 'Lunes a Viernes',
    bestTimeWindow: 'Ma\u00f1ana',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'comodo',
    targetAvatarSecondary: 'desordenado',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 4,
    monthlyDelta: 56,
    yearlyDelta: 672,
    labelImpact: 'Preparar comida en casa ahorra ~56 \u20ac/mes',
    active: true,
    intent: 'gasto_evitado_comida_casa_piloto',
    habit_principle: 'easy',
    tone: 'motivador',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_07',
    format: 'fill_blank',
    text: 'Al revisar mis gastos esta semana, he encontrado un gasto que puedo evitar: ____.',
    blankOptions: [
      {
        label: 'suscripciones o pagos recurrentes que no uso',
        value: 'suscripcion_sin_uso',
        scores: { desordenado: 2 },
      },
      {
        label: 'gastos peque\u00f1os invisibles que se acumulan',
        value: 'gastos_invisibles',
        scores: { desordenado: 2 },
      },
      {
        label: 'compras de comodidad que no son necesarias',
        value: 'comodidad_innecesaria',
        scores: { comodo: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 10,
    habitCategory: 'Revisi\u00f3n de gastos',
    bestDays: 'Domingo, Lunes',
    bestTimeWindow: 'Ma\u00f1ana',
    monthPhase: 'Final',
    targetAvatarPrimary: 'desordenado',
    targetAvatarSecondary: 'comodo',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 7,
    monthlyDelta: 25,
    yearlyDelta: 300,
    labelImpact: 'Revisar gastos semanalmente ahorra ~25 \u20ac/mes',
    active: true,
    intent: 'gasto_evitado_revision_piloto',
    habit_principle: 'satisfying',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_10',
    format: 'fill_blank',
    text: 'En el \u00faltimo plan con amigos, he conseguido controlar el gasto en ____.',
    blankOptions: [
      {
        label: 'consumiciones y rondas de m\u00e1s',
        value: 'rondas',
        scores: { social: 2 },
      },
      {
        label: 'el sitio elegido, optando por algo m\u00e1s econ\u00f3mico',
        value: 'sitio_economico',
        scores: { social: 2 },
      },
      {
        label: 'las compras impulsivas que surgieron en el grupo',
        value: 'compra_grupo',
        scores: { impulsivo: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 12,
    habitCategory: 'Control en planes sociales',
    bestDays: 'Viernes, S\u00e1bado, Domingo',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'social',
    targetAvatarSecondary: 'impulsivo',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 4,
    monthlyDelta: 36,
    yearlyDelta: 432,
    labelImpact: 'Controlar el gasto en planes sociales ahorra ~36 \u20ac/mes',
    active: true,
    intent: 'gasto_evitado_social_piloto',
    habit_principle: 'obvious',
    tone: 'motivador',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_13',
    format: 'fill_blank',
    text: 'Hoy he elegido la opci\u00f3n m\u00e1s econ\u00f3mica en vez de la m\u00e1s c\u00f3moda: ____.',
    blankOptions: [
      {
        label: 'he cocinado en vez de pedir delivery o comida preparada',
        value: 'cocinar_vs_delivery',
        scores: { comodo: 2 },
      },
      {
        label: 'he usado transporte p\u00fablico en vez de taxi o Uber',
        value: 'transporte_publico',
        scores: { comodo: 2 },
      },
      {
        label: 'he planificado la compra en vez de comprar sobre la marcha',
        value: 'compra_planificada',
        scores: { desordenado: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 8,
    habitCategory: 'Elecci\u00f3n econ\u00f3mica vs c\u00f3moda',
    bestDays: 'Lunes a Viernes',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'comodo',
    targetAvatarSecondary: 'desordenado',
    scenarioWeight: 3,
    priorityBase: 8,
    cooldownDays: 4,
    monthlyDelta: 48,
    yearlyDelta: 576,
    labelImpact: 'Elegir opciones m\u00e1s baratas ahorra ~48 \u20ac/mes',
    active: true,
    intent: 'gasto_evitado_comodidad_piloto',
    habit_principle: 'obvious',
    tone: 'motivador',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_16',
    format: 'fill_blank',
    text: 'Hoy he ignorado o cerrado sin comprar una tentaci\u00f3n de gasto en ____.',
    blankOptions: [
      {
        label: 'algo que vi en redes sociales o publicidad',
        value: 'redes_publicidad',
        scores: { impulsivo: 2 },
      },
      {
        label: 'una oferta o descuento que me lleg\u00f3 por mensaje',
        value: 'oferta_mensaje',
        scores: { impulsivo: 2 },
      },
      {
        label: 'un plan o gasto que propuso alguien del grupo',
        value: 'plan_grupo',
        scores: { social: 2 },
      },
    ],
    allowOther: true,
    otherRequiresAI: true,
    aiConfidenceThreshold: 0.70,
    suggestedAmount: 20,
    habitCategory: 'Tentaci\u00f3n de gasto ignorada',
    bestDays: 'Cualquier d\u00eda',
    bestTimeWindow: 'Tarde',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'impulsivo',
    targetAvatarSecondary: 'social',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 4,
    monthlyDelta: 60,
    yearlyDelta: 720,
    labelImpact: 'Ignorar tentaciones de gasto ahorra ~60 \u20ac/mes',
    active: true,
    intent: 'gasto_evitado_tentacion_piloto',
    habit_principle: 'obvious',
    tone: 'motivador',
    difficulty: 'high',
    experimental: true,
  },
];


// ═══════════════════════════════════════════════════════════════════════════════
// AMOUNT — Escenarios de ahorro con importe manual obligatorio
// ═══════════════════════════════════════════════════════════════════════════════

const Q_PILOT_AMOUNT: DailyQuestion[] = [
  {
    id: 'Q_P_03',
    format: 'amount',
    text: 'Si hoy has revisado tus suscripciones y cancelado o reducido alguna que no usabas, ¿cuánto te ahorras al mes?',
    suggestedAmount: 8,
    habitCategory: 'Suscripciones',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Mañana',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'desordenado',
    targetAvatarSecondary: '',
    scenarioWeight: 3,
    priorityBase: 8,
    cooldownDays: 14,
    monthlyDelta: 12,
    yearlyDelta: 144,
    labelImpact: 'Las suscripciones olvidadas cuestan ~12 €/mes',
    active: true,
    intent: 'control_suscripciones',
    habit_principle: 'satisfying',
    tone: 'motivador',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_06',
    format: 'amount',
    text: 'Si hoy has rechazado un plan caro o propuesto una alternativa más barata a tus amigos, ¿cuánto has ahorrado?',
    suggestedAmount: 15,
    habitCategory: 'Planes sociales',
    bestDays: 'Jueves, Viernes, Sábado',
    bestTimeWindow: 'Tarde',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'social',
    targetAvatarSecondary: '',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 3,
    monthlyDelta: 45,
    yearlyDelta: 540,
    labelImpact: 'Proponer alternativas baratas ahorra ~45 €/mes',
    active: true,
    intent: 'control_gasto_social',
    habit_principle: 'attractive',
    tone: 'motivador',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_09',
    format: 'amount',
    text: 'Si hoy has preparado comida en casa en vez de pedir delivery, ¿cuánto has ahorrado?',
    suggestedAmount: 10,
    habitCategory: 'Delivery',
    bestDays: 'Lunes, Martes, Miércoles, Jueves',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'comodo',
    targetAvatarSecondary: '',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 2,
    monthlyDelta: 48,
    yearlyDelta: 576,
    labelImpact: 'Cocinar en casa evita ~4 pedidos semanales de más',
    active: true,
    intent: 'delivery_conveniencia',
    habit_principle: 'easy',
    tone: 'motivador',
    difficulty: 'medium',
    experimental: true,
  },
  {
    id: 'Q_P_12',
    format: 'amount',
    text: 'Si hoy has cerrado una app de compras o ignorado una oferta flash sin comprar nada, ¿cuánto crees que has evitado gastar?',
    suggestedAmount: 20,
    habitCategory: 'Compra impulsiva',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'impulsivo',
    targetAvatarSecondary: '',
    scenarioWeight: 3,
    priorityBase: 9,
    cooldownDays: 3,
    monthlyDelta: 40,
    yearlyDelta: 480,
    labelImpact: 'Cerrar apps de compras sin comprar ahorra ~40 €/mes',
    active: true,
    intent: 'resistencia_compra_impulsiva',
    habit_principle: 'obvious',
    tone: 'motivador',
    difficulty: 'high',
    experimental: true,
  },
  {
    id: 'Q_P_15',
    format: 'amount',
    text: 'Si hoy has identificado un gasto "invisible" que haces casi cada día sin notarlo (café, vending, app…), ¿cuánto suma al mes?',
    suggestedAmount: 5,
    habitCategory: 'Microfugas',
    bestDays: 'Cualquier día',
    bestTimeWindow: 'Noche',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'desordenado',
    targetAvatarSecondary: 'comodo',
    scenarioWeight: 2,
    priorityBase: 8,
    cooldownDays: 5,
    monthlyDelta: 20,
    yearlyDelta: 240,
    labelImpact: 'Identificar microfugas es el primer paso para pararlas',
    active: true,
    intent: 'conciencia_microfugas',
    habit_principle: 'obvious',
    tone: 'reflexivo',
    difficulty: 'low',
    experimental: true,
  },
  {
    id: 'Q_P_18',
    format: 'amount',
    text: 'Si esta semana has controlado los gastos en salidas nocturnas (copas extra, taxis, rondas), ¿cuánto menos has gastado de lo normal?',
    suggestedAmount: 15,
    habitCategory: 'Escalada social',
    bestDays: 'Lunes, Domingo',
    bestTimeWindow: 'Mañana',
    monthPhase: 'Cualquiera',
    targetAvatarPrimary: 'social',
    targetAvatarSecondary: 'impulsivo',
    scenarioWeight: 3,
    priorityBase: 8,
    cooldownDays: 7,
    monthlyDelta: 45,
    yearlyDelta: 540,
    labelImpact: 'Controlar las noches que se alargan ahorra ~45 €/mes',
    active: true,
    intent: 'control_escalada_social',
    habit_principle: 'satisfying',
    tone: 'motivador',
    difficulty: 'high',
    experimental: true,
  },
];

// ═══════════════════════════════════════════════════════════════════════════════
// Banco piloto completo
// ═══════════════════════════════════════════════════════════════════════════════

/**
 * 12 preguntas piloto funcionales y listas para test.
 * Distribuidas en: 6 fill_blank + 6 amount.
 * Cubren los 4 avatares activos: comodo, social, impulsivo, desordenado.
 */
export const PILOT_QUESTIONS_BANK: DailyQuestion[] = [
  ...Q_PILOT_FILL_BLANK,
  ...Q_PILOT_AMOUNT,
];
