-- 11 · mart_kpi_summary: una fila con los KPIs titulares (scorecards de Looker).
CREATE OR REPLACE TABLE `{{project}}.{{an}}.mart_kpi_summary` AS
WITH p AS (SELECT * FROM `{{project}}.{{an}}.params`),
k AS (SELECT * FROM `{{project}}.{{an}}.mart_kpi_daily` WHERE date = CURRENT_DATE('Europe/Madrid')),
s AS (SELECT * FROM `{{project}}.{{an}}.mart_user_savings`),
f AS (SELECT * FROM `{{project}}.{{an}}.mart_funnel_user`),
g AS (SELECT * FROM `{{project}}.{{an}}.mart_goals`),
r AS (SELECT * FROM `{{project}}.{{an}}.mart_retention_dn`),
l AS (SELECT * FROM `{{project}}.{{an}}.fct_ledger`)
SELECT
  CURRENT_TIMESTAMP()                                              AS computed_at,
  (SELECT registered_users FROM k)                                 AS registered_users,
  (SELECT mau FROM k)                                              AS active_users_30d,
  (SELECT wau FROM k)                                              AS active_users_7d,
  (SELECT savers_30d FROM k)                                       AS savers_30d,
  (SELECT stickiness_dau_mau FROM k)                               AS stickiness_dau_mau,
  (SELECT SUM(total_saved) FROM s)                                 AS total_saved,
  (SELECT SUM(total_net_saved) FROM s)                             AS total_net_saved_declared,
  (SELECT SUM(opening_balance) FROM s)                             AS opening_balance_v1,
  (SELECT IFNULL(SUM(net_saving_amount), 0) FROM l WHERE is_v2_live) AS net_saved_since_cutover,
  (SELECT SUM(current_balance) FROM s)                             AS total_balance,
  (SELECT AVG(run_rate_annual) FROM s WHERE first_saving_date IS NOT NULL)  AS avg_run_rate_annual_savers,
  (SELECT APPROX_QUANTILES(run_rate_annual, 2)[OFFSET(1)] FROM s WHERE first_saving_date IS NOT NULL) AS median_run_rate_annual_savers,
  (SELECT AVG(consistency_weekly) FROM s WHERE first_saving_date IS NOT NULL) AS avg_consistency_weekly,
  (SELECT AVG(savings_rate_of_income) FROM s WHERE savings_rate_of_income IS NOT NULL) AS avg_savings_rate_of_income,
  (SELECT SAFE_DIVIDE(COUNTIF(activated_7d), COUNT(*)) FROM f)     AS activation_rate_7d,
  (SELECT SAFE_DIVIDE(COUNTIF(step_4_first_saving), COUNT(*)) FROM f) AS saver_conversion,
  (SELECT retention_rate FROM r WHERE dn = 7)                      AS retention_d7,
  (SELECT retention_rate FROM r WHERE dn = 30)                     AS retention_d30,
  (SELECT COUNTIF(status = 'active') FROM g)                       AS goals_active,
  (SELECT COUNTIF(is_completed) FROM g)                            AS goals_completed,
  (SELECT AVG(progress_pct) FROM g WHERE status = 'active')        AS avg_goal_progress,
  (SELECT SAFE_DIVIDE(COUNTIF(is_at_risk), COUNT(*)) FROM s)       AS at_risk_share,
  (SELECT SUM(current_balance) FROM s) * (SELECT bank_margin_annual_pct FROM p) * (SELECT ltv_years FROM p) AS est_ltv_total,
  (SELECT MAX(recorded_at) FROM `{{project}}.{{raw}}.savings_transactions`) AS last_ledger_record_at,
  (SELECT MAX(event_ts) FROM `{{project}}.{{an}}.stg_events`)      AS last_posthog_event_at;
